apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.vault.secret2.name }}
  namespace: {{ .Values.namespace }}
spec:
  destination:
    create: true
    name: {{ .Values.vault.secret2.name }}
    type: {{ .Values.vault.secret2.type }}
  mount: {{ .Values.vault.secret2.mount }}
  path: {{ .Values.vault.secret2.path }}
  refreshAfter: 30s
  type: kv-v2  
  